Repository raksul/go-clickup, pull requests merged in 2022-01, with the labels that each got.

#10 Add a license file.
  LICENSE
Labels: size/S

#14 Implement create task attachment
  README.md
  clickup/attachments.go
  clickup/attachments_test.go
  clickup/client.go
Labels: size/L

#19 Add set custom field value
  README.md
  clickup/custom_fields.go
Labels: size/M

#20 Add view service
  clickup/client.go
  clickup/views.go
Labels: size/L

#22 Follow golang practice
  clickup/views.go
Labels: size/XS

#23 Add task template
  README.md
  clickup/client.go
  clickup/task_templates.go
Labels: size/M

#24 Add shared hierarchy
  README.md
  clickup/client.go
  clickup/shared_hierarchy.go
Labels: size/M

#25 Add get access token
  README.md
  clickup/authorization.go
Labels: size/M
